### ISSUE TITLE
Problem running kafka console with docker

### ISSUE THREAD

**Issue by tabouzeid** [stealthly/docker-kafka-webconsole#1]
Hey, I added this to my docker-compose.yml and it seems to startup fine until at the end is says it's running in the background and then exits killing everything... any idea what's going on there?

kafkaui:
  image: stealthly/docker-kafka-webconsole
  ports:
    - "9000:9000"
  links:
    - zookeeper:zk
# 

kafkaui_1    | (Starting server. Type Ctrl+D to exit logs, the server will remain in background)
kafkaui_1    |
kafkaui_1    |
desktop_kafkaui_1 exited with code 0

**Comment by joestein** [comment]
Hey @tabouzeid we have actually stopped using that specific web console and have been looking at using https://github.com/yahoo/kafka-manager instead. We will update this with that in the near future.

**Comment by tabouzeid** [comment]
great, thx for the response
